apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-startup
  namespace: stocks-sports
spec:
  encryptedData:
    users.sql: AgCGUz6cCXj5vORdFg0ECzUjZvhZdY2khGDa9/ITYP2wI6olhEzuKdEwo3zgerpMqWo5NmOU9Gnq/9AuNxmmh73LfiK4An+DKWld6Na+FSou9tjCH4An8tH+Enr9AQDBW3zz0joJG8/th1AO4YsYF67mn04lctSzhUluLrk2j7ck5nvKRi9ILe98C02FjS2HqV4LOvqMp2e46l9Ctf8KxrFn5uFINMr4DuVOZhNHz0u+sp+ozgsOO5sdhHHfhaOp59kveRL9J8NP1bjkhPYT7XqWETLCN66kh3hztlFdnWItdDsYKxhrYxHBMK0LXHHBHYPVUBQQAGIH0LF9VRzT78Zei+Xca3sUul9ZuvbaWyFPzNp6EyTcGUW0tCuESjCwVBTJeOWWBJI1D+Uj1wEXEXxyqpmv9y4I80jZHF6xSGdUFMJz+0B0YFr2Pvd8EBlQ3V8GCstA6m6AXrHJkBHuTShclGBNRduTA3NlRB5sT3a/hyxygsLwjIkK2OIx3Pd5ZYNytgUcmG6JzGn8rGQOFH6OYT2+/8JY0tQ50bWtj/zszLNqHIPbwxz4xybxifHq8F3eoCTLgASLN7Y440rRPTYdAQ+jbnaTAqlIwFkUYUikhM2aCicDYXtrfpnaBPo1Hnxqsphubi0L72gkYL0jsyxh9l62mol8VTsq/Y3H4HmwYuB1onkDzY/D2lCWK/WiHinSgzMjQGyBO07GhKQ5wmOxrlHylygtCGozPFzRNZDgEwALDkUN9DYKwfQ5hybDlBa68PV0K7pnn6hX06+jZ5+gOtCq5CuQI6fj0vZvulTYVQWTF007ms7olzrnmbQrp4rx1Vc6+8YisTOOPgYGdxsNQ0QirduhCfP312kfKVTjUJEn2/rflTZrGDf2abPiPpBOKnypBSpw9rCR+2mvePRfe5kti2Xje+Kxxc0VwWf8rC3je6lBbw+cYZSrhjcz2eks1acjQD/jqRT7d+ZbeJJIl0vm2374uNOr1bth/hTM6I978KmO4KOsPmFsrjhUJvTiZ25vWlGAqSeBEzVXFC9WXR96AzMNchrB/uLEiZgf2aPz3BtyDmS8DFj3qauXxvY5TDUUdz4QTOTTTZOdAFtX58Enll4LJnXyc+hqe1TeBlo6hhz7wnON44l7C6LIMtzFU8P8+q6Vl/jyXR3t9TrK0g8ImU39L6CHfXrOLUHt6TaljJtLfZM3nPoyZoOit5B3zzQleObvaGriUXThOWsBec9vcTcyENvbvGI0BUZIo7zh/Y0gHpC4sor78pF4+Ds7Izenit0w04ItW7QKKdreELHuuEkkgGOxg9D84gMmIhbRuvMMOGdDaDTK+4Z7v66wg+yMVVCK744DWe4iDRxN9/2suBvqojOyU+c=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-startup
      namespace: stocks-sports

