apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sports-daily-population
  namespace: stocks-sports
spec:
  schedule: "15 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sports-daily-population
              image: loganballard/stocks-sports-jobs:0.0.10
              args: ["--verbose", "--sports", "--production"]
              env:
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: mysql-credentials
                      key: admin_pass
                - name: ODDS_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: sports-odds-api-key
                      key: key
                - name: DB_USER
                  value: stocks_sports_admin
                - name: DB_HOST
                  value: mysql
                - name: DB_PORT
                  value: "3306"
                - name: DB_NAME
                  value: stocks_sports
          restartPolicy: OnFailure
      backoffLimit: 3
